#!/usr/bin/env python
# -*- language: python; coding: utf-8 -*-
# autoloa.py - Automatic pantheon generation.
# Copyright 2014 - 2015 Rob Myers <rob@robmyers.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import datetime, json, sys
import pytumblr

import descriptions

if len(sys.argv) != 2:
    print "Usage: autoloa <config.json>"
    sys.exit(1)

with open(sys.argv[1]) as credentials_file:
    config = json.load(credentials_file)

def postDescription(name, description):
    global config
    client = pytumblr.TumblrRestClient(
        config['consumer_key'],
        config['consumer_secret'],
        config['oauth_token'],
        config['oauth_token_secret'])
    client.create_text(config['blog'], state='published',
                       title=name.encode("utf-8"),
                       body=description.encode("utf-8"))

if __name__ == '__main__':
    now = datetime.datetime.now().isoformat()
    entities = descriptions.describePantheon(now)
    #for entity in entities:
    postDescription(entities[0][0], entities[0][1])
